from flask import Flask, jsonify, request
import joblib
import numpy as np
import pandas as pd
import time
import os
from flask_cors import CORS

app = Flask(__name__)
CORS(app) # Enable CORS just in case of web-based testing

# --- Asset Configuration ---
MODEL_PATH = "Ultimate_NIDS_Model.pkl"
SCALER_PATH = "Ultimate_Scaler.pkl"
ENCODER_PATH = "Ultimate_LabelEncoder.pkl"
FEATURES_PATH = "Feature_List.pkl"

def load_ml_assets():
    """Loads the model and preprocessing tools generated by train_model.py"""
    if not all(os.path.exists(f) for f in [MODEL_PATH, SCALER_PATH, ENCODER_PATH, FEATURES_PATH]):
        print("⚠️ Warning: Model assets not found. Generating dummy predictions for testing.")
        return None, None, None, None
    
    try:
        model = joblib.load(MODEL_PATH)
        scaler = joblib.load(SCALER_PATH)
        encoder = joblib.load(ENCODER_PATH)
        features = joblib.load(FEATURES_PATH)
        print("✅ ML Assets loaded successfully.")
        return model, scaler, encoder, features
    except Exception as e:
        print(f"❌ Error loading assets: {e}")
        return None, None, None, None

model, scaler, encoder, features_list = load_ml_assets()

@app.route('/threats', methods=['GET'])
def get_threats():
    """
    Simulates network traffic analysis and returns a threat object 
    formatted for the Android Room Database.
    """
    # 1. Simulate incoming data or perform real prediction
    if model and scaler and encoder and features_list:
        # Generate random data matching feature shape for simulation
        raw_data = np.random.rand(1, len(features_list)) * 100
        df = pd.DataFrame(raw_data, columns=features_list)
        
        # Predict
        scaled_data = scaler.transform(df)
        pred_idx = model.predict(scaled_data)[0]
        verdict = str(encoder.inverse_transform([pred_idx])[0])
        
        # Get confidence
        probs = model.predict_proba(scaled_data)[0]
        confidence = float(np.max(probs)) * 100
    else:
        # Fallback for testing if model isn't trained yet
        verdicts = ["DDoS", "PortScan", "Bot", "Infiltration"]
        verdict = random.choice(verdicts)
        confidence = round(np.random.uniform(85.0, 99.9), 2)

    # 2. Construct the JSON object exactly as the Android App expects
    # Note: Android Room/Retrofit expects these exact keys
    threat_data = {
        "id": int(time.time() * 1000), # Unique ID based on epoch
        "verdict": verdict,
        "confidence": round(confidence, 2),
        "timestamp": int(time.time()),
        "userAction": "PENDING"
    }

    print(f"📡 Sending Threat: {verdict} ({confidence}%) to Android App")
    
    # Return as a List because the App expects List<ThreatEntity>
    return jsonify([threat_data])

@app.route('/ping', methods=['GET'])
def ping():
    """Simple health check endpoint"""
    return jsonify({"status": "online", "message": "NIDS Server is reachable"})

if __name__ == '__main__':
    # CRITICAL: host='0.0.0.0' allows connections from the Android Emulator
    # The Emulator connects via http://10.0.2.2:5000
    print("🚀 NIDS Backend starting on http://0.0.0.0:5000")
    app.run(host='0.0.0.0', port=5000, debug=True)